### ISSUE TITLE
One invalid version causes entire autoreport to fail

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1361]
@dorey, should we add exception handling and logging to the `to_formpack_schema()` call for each version at https://github.com/kobotoolbox/kpi/blob/1aaa197e1302a0c6fb9f125bcf5a4fcdbf006e14/kobo/apps/reports/report_data.py#L47?

Example failure: https://app.intercom.io/a/apps/s6hn3a8q/respond/inbox/mentions/conversations/10429702434

**Comment by jnm** [comment]
(duplicating info from Intercom for convenience)

Example:

* http://sentry.kbtdev.org/kobo/kpi/issues/1624/
* Our PROD, UID vsPZHjoBaTUqJhPq9B88jP
* Reproduction of the exception in the Django shell:

```
>>> AssetVersion.objects.get(uid='vsPZHjoBaTUqJhPq9B88jP').to_formpack_schema()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ubuntu/src/kpi/kpi/models/asset_version.py", line 52, in to_formpack_schema
    'content': expand_content(self._deployed_content()),
  File "/home/ubuntu/src/kpi/kpi/models/asset_version.py", line 45, in _deployed_content
    deprecated_autoname=True)
  File "/home/ubuntu/src/kpi/kpi/utils/kobo_to_xlsform.py", line 96, in to_xlsform_structure
    expand_rank_and_score_in_place(surv)
  File "/home/ubuntu/src/kpi/kpi/utils/kobo_to_xlsform.py", line 110, in expand_rank_and_score_in_place
    _parse_contents_of_kobo_structures(surv)
  File "/home/ubuntu/src/kpi/kpi/utils/kobo_to_xlsform.py", line 42, in _parse_contents_of_kobo_structures
    result = current_handler.handle_row(row)
  File "/home/ubuntu/src/kpi/kpi/utils/xlsform_preprocessors/koboscore_handler.py", line 106, in handle_row
    " (or 'end_score')" % row.get('type'))
TypeError: 'end score': KoboScore groups can only contain rows with type='score__row' (or 'end_score')
```

**Comment by jnm** [comment]
Decided to log an error and continue: https://github.com/kobotoolbox/kpi/commit/e1c0dac724416639885591f887143f748c3fe45f
