### ISSUE TITLE
Cannot create or save projects if search index corrupt

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1368]
This kind of failure is unacceptable; if Haystack/Whoosh doesn't have its house in order, simply log the exception and carry on with creating or saving the `Asset`:
```
Traceback (most recent call last):
  File "<console>", line 4, in <module>
  File "/srv/src/kpi/kpi/models/asset.py", line 74, in create
    created= super(TaggableModelManager, self).create(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/src/kpi/kpi/models/asset.py", line 577, in save
    super(Asset, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/srv/src/kpi/kpi/models/object_permission.py", line 246, in save
    super(ObjectPermissionMixin, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/haystack/signals.py", line 52, in handle_save
    index.update_object(instance, using=using)
  File "/usr/local/lib/python2.7/dist-packages/haystack/indexes.py", line 278, in update_object
    backend.update(self, [instance])
  File "/usr/local/lib/python2.7/dist-packages/haystack/backends/whoosh_backend.py", line 178, in update
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/haystack/backends/whoosh_backend.py", line 126, in setup
    self.index = self.storage.open_index(schema=self.schema)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/structfile.py", line 191, in read_varint
    return read_varint(self.read)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by jnm** [comment]
Whoosh will be removed.
