### ISSUE TITLE
New exports "processing" indefinitely

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1522]
To reproduce:

- Go to Data > Exports, select XLS or CSV. Click "Export". 

![image](https://user-images.githubusercontent.com/15673694/35162767-48386f26-fd12-11e7-92a9-81f09320b1a9.png)

**Comment by jnm** [comment]
We may be getting rate-limited by Amazon S3? The workers are getting stuck—sitting, not doing any work—and there's a lot of this in the log:
```
[2018-01-19 19:21:36,169: INFO/Worker-114] Resetting dropped connection: s3.amazonaws.com
```

**Comment by jnm** [comment]
S3 is probably a red herring, but we'll see. To reproduce, this evil loop in the Django shell works pretty well:
```python
t = ExportTask.objects.filter(user__username='not_a_real_user').last()
while True:
    n = ExportTask()
    n.user = t.user
    n.data = t.data.copy()
    n.save()
    export_in_background.delay(n.uid)
    sys.stdout.write('.')
    time.sleep(0.1)
```
These errors show up in the Celery log while running the loop:
```python
Traceback (most recent call last):                                              
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)                                           
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)                                            
  File "/home/ubuntu/src/kpi/kpi/tasks.py", line 19, in export_in_background    
    export_task.run()                                                           
  File "/home/ubuntu/src/kpi/kpi/models/import_export_task.py", line 116, in run
    self.save(update_fields=['status', 'messages', 'data'])                     
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)                     
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/django/db/models/base.py", line 831, in _save_table
    raise DatabaseError("Save with update_fields did not affect any rows.") 
```
```python
Traceback (most recent call last):                                              
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)                                           
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)                                            
  File "/home/ubuntu/src/kpi/kpi/tasks.py", line 19, in export_in_background    
    export_task.run()                                                           
  File "/home/ubuntu/src/kpi/kpi/models/import_export_task.py", line 82, in run 
    _refetched_self = self._meta.model.objects.get(pk=self.pk)                  
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)                  
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name                                                
Exception: ExportTask matching query does not exist.
```
```python
Traceback (most recent call last):                                              
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)                                           
  File "/home/ubuntu/.virtualenvs/kpi/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)                                            
  File "/home/ubuntu/src/kpi/kpi/tasks.py", line 19, in export_in_background    
    export_task.run()                                                           
  File "/home/ubuntu/src/kpi/kpi/models/import_export_task.py", line 91, in run 
    self._meta.model_name)                                                      
Exception: only recently created exporttasks can be executed 
```
Of course, there's a good deal of `Resetting dropped connection`, too, but I'm not sure it matters.

**Comment by jnm** [comment]
Hm. `ExportTask matching query does not exist` is almost certainly the race condition described by http://docs.celeryproject.org/en/latest/userguide/tasks.html#database-transactions. Of course, the easy `on_commit` fix for this is in Django 1.9, and for 1.8, we have to switch our database backend: https://django-transaction-hooks.readthedocs.io/en/latest/#why-database-backends. The other two errors smell like a similar ilk.

A separate issue, though, is the Celery workers just stalling / giving up without any explanation. Testing on kf.master, I get a lot of
```
UserWarning: MongoClient opened before fork. Create MongoClient with connect=False, or create client after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#using-pymongo-with-multiprocessing
```
Maybe that's to blame.

**Comment by jnm** [comment]
"Almost certainly" = definitely not. Bypassing
https://github.com/kobotoolbox/kpi/blob/045f5cc20a096f716a450433b43f5c5a2b932c8d/kpi/models/import_export_task.py#L525
got rid of `ExportTask matching query does not exist`; [manually committing](https://docs.djangoproject.com/en/1.8/topics/db/transactions/#transactions) had no effect.

**Comment by jnm** [comment]
Next up to try: https://github.com/dcrosta/flask-pymongo/issues/87
