### ISSUE TITLE
Docker builds fail with `ImportError: No module named django_digest`

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1567]
An intermittent problem. Sample:
```
Step 19/25 : RUN python manage.py collectstatic --noinput
 ---> Running in b751a1dd78e7
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_digest
The command '/bin/sh -c python manage.py collectstatic --noinput' returned a non-zero code: 1
```

**Comment by jnm** [comment]
The [second `pip-sync`](https://github.com/kobotoolbox/kpi/blob/e5ba1aac8cb6d6a8e8a97e10bcf5e9436969b05e/Dockerfile#L29-L37) that runs in `498f9d0f6bcc` actually changes the `django_digest` egg link location from `/src/django-digest` to `/srv/src/kpi/src/django-digest`, where it gets erased by [`RUN rm -rf "${KPI_SRC_DIR}"`](https://github.com/kobotoolbox/kpi/blob/e5ba1aac8cb6d6a8e8a97e10bcf5e9436969b05e/Dockerfile#L77).

    john@scrappy:/tmp/kpi$ for i in $(docker history -q e1ed7284f051 | grep -v missing)
    > do
    > echo In image $i, django-digest lives in $(docker run --rm $i head -n 1 /usr/local/lib/python2.7/dist-packages/django-digest.egg-link)
    > done
    In image e1ed7284f051, django-digest lives in /srv/src/kpi/src/django-digest
    In image c83cc695db3d, django-digest lives in /srv/src/kpi/src/django-digest
    In image 4a6dce12692c, django-digest lives in /srv/src/kpi/src/django-digest
    In image 6df08b1c1800, django-digest lives in /srv/src/kpi/src/django-digest
    In image cefb88f03225, django-digest lives in /srv/src/kpi/src/django-digest
    In image dccf70db4104, django-digest lives in /srv/src/kpi/src/django-digest
    In image 8fdca7844717, django-digest lives in /srv/src/kpi/src/django-digest
    In image 4671d5f035fe, django-digest lives in /srv/src/kpi/src/django-digest
    In image 00030cad46cf, django-digest lives in /srv/src/kpi/src/django-digest
    In image b538d8980506, django-digest lives in /srv/src/kpi/src/django-digest
    In image 34371c50c452, django-digest lives in /srv/src/kpi/src/django-digest
    In image 674d2e5c0902, django-digest lives in /srv/src/kpi/src/django-digest
    In image 498f9d0f6bcc, django-digest lives in /srv/src/kpi/src/django-digest
    In image 3d442fbb31fd, django-digest lives in /src/django-digest
    In image 1a2a128c8c83, django-digest lives in /src/django-digest
    In image fac3863befd1, django-digest lives in /src/django-digest
    In image b5cbc09fe065, django-digest lives in /src/django-digest
    In image e8d8609922b8, django-digest lives in /src/django-digest
