### ISSUE TITLE
XLSForm that deploys in KC fails in KPI

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1957]
"Incorrect translation count": either make this work, or, if the XLSForm is really broken, then display a useful error to the user. File to reproduce: [minimal500.xls.zip](https://github.com/kobotoolbox/kpi/files/2303917/minimal500.xls.zip)
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/src/kpi/kpi/views.py", line 1103, in deployment
    serializer.save()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/srv/src/kpi/kpi/serializers.py", line 730, in create
    active=validated_data.get('active', False))
  File "/srv/src/kpi/kpi/deployment_backends/mixin.py", line 25, in deploy
    self.connect_deployment(backend=backend, active=active)
  File "/srv/src/kpi/kpi/deployment_backends/mixin.py", line 13, in connect_deployment
    DEPLOYMENT_BACKENDS[backend](self).connect(**kwargs)
  File "/srv/src/kpi/kpi/deployment_backends/kobocat_backend.py", line 258, in connect
    'form_title': self.asset.name,
  File "/srv/src/kpi/kpi/models/asset.py", line 410, in to_xls_io
    sys.exc_info()[2]
  File "/srv/src/kpi/kpi/models/asset.py", line 399, in to_xls_io
    ss_dict = self.ordered_xlsform_content(**kwargs)
  File "/srv/src/kpi/kpi/models/asset.py", line 362, in ordered_xlsform_content
    self._xlsform_structure(content, ordered=True, kobo_specific=kobo_specific_types)
  File "/srv/src/kpi/kpi/models/asset.py", line 185, in _xlsform_structure
    **opts)
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 101, in flatten_to_spreadsheet_content
    _od[sheet_name] = _sheet_to_ordered_dicts(sheet_name, rows)
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 84, in _sheet_to_ordered_dicts
    _row_to_ordered_dict(row, OrderedDict.fromkeys(ordered_cols)) for row in rows
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 59, in _row_to_ordered_dict
    col_order=dest.keys(),
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/flatten_content.py", line 180, in _flatten_translated_fields
    ), o_row)
Exception: asset.content improperly formatted for XLS export: ValueError(u'Incorrect translation count: "label"', {u'select_from_list_name': u'pgrnlist', u'name': u'PP_HavePGRN', u'default': u'YES', u'section': u'PP', u'required': True, u'label': [u'If you are updating information about a project that you have already previously registered in this tool, then please enter your Project GAM Reference Number below.', u'Si vous mettez \xe0 jour des informations sur un projet que vous avez d\xe9j\xe0 enregistr\xe9 dans cet outil, veuillez entrer votre num\xe9ro de r\xe9f\xe9rence de projet MGA ci-dessous.', u'\u0625\u0630\u0627 \u0643\u0646\u062a \u062a\u0642\u0648\u0645 \u0628\u062a\u062d\u062f\u064a\u062b \u0645\u0639\u0644\u0648\u0645\u0627\u062a \u062d\u0648\u0644 \u0645\u0634\u0631\u0648\u0639 \u0642\u0645\u062a \u0628\u062a\u0633\u062c\u064a\u0644\u0647 \u0628\u0627\u0644\u0641\u0639\u0644 \u0641\u064a \u0647\u0630\u0647 \u0627\u0644\u0623\u062f\u0627\u0629 \u060c \u0641\u0627\u0644\u0631\u062c\u0627\u0621 \u0625\u062f\u062e\u0627\u0644 \u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u0645\u0631\u062c\u0639 \u0627\u0644\u0645\u0634\u0631\u0648\u0639 \u0645\u0624\u0634\u0631 \u0627\u0644\u0646\u0648\u0639 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a \u0648 \u0627\u0644\u0639\u0645\u0631 \u0623\u062f\u0646\u0627\u0647.'], u'type': u'select_one'})
```

**Comment by jnm** [comment]
leaving this open for the "display a useful error" component.
the backend exception is tracked at https://github.com/kobotoolbox/formpack/issues/175
