### ISSUE TITLE
Better error message for import failure (part II)

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1962]
## Steps to Reproduce

1. …
2. …
3. …

**Comment by magicznyleszek** [comment]
I created PR that adds filename to the error notification - this is known information, so no backend changes were needed. As for more detailed information about sheet/row - backend magicians will need to tell if this is possible @jnm  @noliveleger

**Comment by joeflack4** [comment]
@magicznyleszek Thank you for the progress thus far.

**Comment by jnm** [comment]
Should also verify that the invalid IANA language code warning message is shown. It should look like what's displayed by http://opendatakit.org/xlsform/

**Comment by joeflack4** [comment]
That looks really useful.

For the record, the intentionally invalid .xlsx file I attached in the OP produces the following error message in pyxform 1.3.1:
```
Joe:Desktop joeflack4$ xls2xform invalid\ xlsform.xlsx test.xml
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/xls2xform", line 11, in <module>
    sys.exit(main_cli())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyxform/xls2xform.py", line 137, in main_cli
    enketo=args.enketo_validate)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyxform/xls2xform.py", line 19, in xls2xform_convert
    json_survey = xls2json.parse_file_to_json(xlsform_path, warnings=warnings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyxform/xls2json.py", line 1007, in parse_file_to_json
    workbook_dict, default_name, default_language, warnings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyxform/xls2json.py", line 418, in workbook_to_json
    "a option with no name. " + info)
pyxform.errors.PyXFormError: On the choices sheet there is a option with no name. [list_name : school_list - Generic]
```

**Comment by jeverling** [comment]
Another issue with import failure messages right now is that when the filename of the XLSForm is longer, the error message itself isn't visible.

![image](https://github.com/kobotoolbox/kpi/assets/121946/89b233a2-5a39-4f55-9327-0ba3d6b4185c)

In this case, the error message is `SyntaxError: xls upload must have one of these sheets: survey, library`.
