### ISSUE TITLE
DRF browsable API returns 500 for `/me` endpoint

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2301]
Workaround: `/me?format=json` does return the expected response.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 706, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 641, in get_context
    raw_data_patch_form = self.get_raw_data_form(data, view, 'PATCH', request)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 559, in get_raw_data_form
    data = {k: v for (k, v) in serializer.data.items()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 560, in <dictcomp>
    if not isinstance(serializer.fields[k],
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/utils/serializer_helpers.py", line 148, in __getitem__
    return self.fields[key]
KeyError: 'available_sectors'
```

**Comment by jnm** [comment]
Still happening, except now only when logged out:

1. Log out;
1. Go to `/me`;
1. Observe 500;
1. Go to `/me?format=json`;
1. Observe 200;
1. Log in;
1. Go to `/me`;
1. Observe 200.

```
KeyError: 'message'
  File "django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "rest_framework/renderers.py", line 706, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "rest_framework/renderers.py", line 641, in get_context
    raw_data_patch_form = self.get_raw_data_form(data, view, 'PATCH', request)
  File "rest_framework/renderers.py", line 559, in get_raw_data_form
    data = {k: v for (k, v) in serializer.data.items()
  File "rest_framework/renderers.py", line 560, in <dictcomp>
    if not isinstance(serializer.fields[k],
  File "rest_framework/utils/serializer_helpers.py", line 148, in __getitem__
    return self.fields[key]
```
https://sentry.kbtdev.org/kobo/kpi-backend/issues/300789/?query=is:unresolved

**Comment by noliveleger** [comment]
PR for `Python3` seems to fix this. 
I can reproduce locally the error with branch `two-databases`:
![Screen Shot 2019-10-24 at 09 54 13](https://user-images.githubusercontent.com/24226825/67492488-7bfe8e80-f644-11e9-89cb-a954635f7482.png)


but it disappears after switching to `Python3`:
![Screen Shot 2019-10-24 at 09 54 23](https://user-images.githubusercontent.com/24226825/67492374-540f2b00-f644-11e9-9844-9195f1075ea6.png)

Maybe because of a conflict in `DRF` version.
