### ISSUE TITLE
ValueError: Cannot quote parameter value [] of type <type 'list'> during migration

### ISSUE THREAD

**Issue by sarveshwaranj** [kobotoolbox/kpi#2318]
Operations to perform:
  Synchronize unmigrated apps: loginas, mptt, corsheaders, webpack_loader, staticfiles, messages, markitup, debug_toolbar, markdownx, service_health, django_extensions, private_storage, rest_framework, haystack, superuser_stats, constance
  Apply all migrations: authtoken, oauth2_provider, sessions, reversion, help, hub, django_celery_beat, admin, database, external_integrations, auth, django_digest, contenttypes, taggit, registration, kpi, hook
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying hook.0003_add_subset_fields_to_hook_model...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 179, in add_field
    self._remake_table(model, create_fields=[field])
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 77, in _remake_table
    self.effective_default(field)
  File "/home/ewall-lap-24/Desktop/kpienv2/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 46, in quote_value
    raise ValueError("Cannot quote parameter value %r of type %s" % (value, type(value)))
ValueError: Cannot quote parameter value [] of type <type 'list'>
How to solve this??

**Comment by hoseinfo** [comment]
same error,
any fix?

**Comment by KamiTzayig** [comment]
same, did you find a solution @hoseinfo ?
