### ISSUE TITLE
Travis CI passing when it shouldn't

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2754]
This build "passed": https://travis-ci.org/github/kobotoolbox/kpi/builds/717509996
…but given its log, it should have failed:
```
$ npm run test

> kpi@0.1.1 test /home/travis/build/kobotoolbox/kpi
> webpack --config webpack/test.config.js --colors && mocha-chrome test/tests.html

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
no kpi-root-path meta tag set. defaulting to ""
[chrome-exception] { timestamp: 1597305607907.404,
  exceptionDetails: 
   { exceptionId: 2,
     text: 'Uncaught',
     lineNumber: 50,
     columnNumber: 71,
     url: 'webpack://tests/./jsapp/js/constants.es6?',
     stackTrace: { callFrames: [Array] },
     exception: 
      { type: 'object',
        subtype: 'error',
        className: 'TypeError',
        description: 'TypeError: t is not a function\n    at Module.eval (webpack://tests/./jsapp/js/constants.es6?:51:72)\n    at eval (webpack://tests/./jsapp/js/constants.es6?:314:30)\n    at Module../jsapp/js/constants.es6 (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:218:1)\n    at __webpack_require__ (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:21:30)\n    at eval (webpack://tests/./jsapp/js/utils.es6?:42:70)\n    at Module../jsapp/js/utils.es6 (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:254:1)\n    at __webpack_require__ (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:21:30)\n    at eval (webpack://tests/./jsapp/xlform/src/mv.skipLogicHelpers.coffee?:765:41)\n    at Object../jsapp/xlform/src/mv.skipLogicHelpers.coffee (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:508:1)\n    at __webpack_require__ (file:///home/travis/build/kobotoolbox/kpi/test/compiled/app.js:21:30)',
        objectId: '{"injectedScriptId":2,"id":3}',
        preview: [Object] },
     executionContextId: 2 } }
```

**Comment by jnm** [comment]
Travis CI is dead :skull:
