### ISSUE TITLE
npm run build failing

### ISSUE THREAD

**Issue by amks1** [kobotoolbox/kpi#3052]
## Description

I'm trying to update my kpi docker directly on our production server. I forked the latest kpi code to our github repo and made some slight changes (changed logo and some text - nothing that would affect any functionality). However I'm not able to do an `npm run build`, it gives me errors.

## Steps to Reproduce

1. I logged into the docker `docker exec -it kobofe_kpi_1 /bin/bash`
2. Did a git pull to overwrite existing files on the master branch (I backed up the existing master branch just in case):
```
git fetch origin main
git reset --hard origin/main
```
3. Tried `npm run build` (didn't work)
4. Also ran `manage.py collectstatic` which worked
5. exit and restarted container 

## Expected behavior 

Should update the production files and update the kf site. 

## Actual behavior 

Got this error on `npm run build`:
```
kpi@0.1.1 build /srv/src/kpi
webpack --config webpack/prod.config.js
/srv/src/kpi/node_modules/webpack-cli/bin/cli.js:93
throw err;
^
Error: Cannot find module ‘webpack-extract-translation-keys-plugin’
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (/srv/src/kpi/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
at Object. (/srv/src/kpi/webpack/webpack.common.js:2:38)
at Module._compile (/srv/src/kpi/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
at Object.Module._extensions…js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (/srv/src/kpi/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
at Object. (/srv/src/kpi/webpack/prod.config.js:5:23)
at Module._compile (/srv/src/kpi/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
at Object.Module._extensions…js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (/srv/src/kpi/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
at WEBPACK_OPTIONS (/srv/src/kpi/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
at requireConfig (/srv/src/kpi/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
at /srv/src/kpi/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
at Array.forEach ()
at module.exports (/srv/src/kpi/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
at yargs.parse (/srv/src/kpi/node_modules/webpack-cli/bin/cli.js:71:45)
at Object.parse (/srv/src/kpi/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
at /srv/src/kpi/node_modules/webpack-cli/bin/cli.js:49:8
at Object. (/srv/src/kpi/node_modules/webpack-cli/bin/cli.js:366:3)
at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kpi@0.1.1 build: webpack --config webpack/prod.config.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kpi@0.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-03-06T21_56_59_193Z-debug.log
```

And the debug log gives this:

```
0 info it worked if it ends with ok
1 verbose cli [ ‘/usr/bin/node’, ‘/usr/bin/npm’, ‘run’, ‘build’ ]
2 info using npm@6.14.5
3 info using node@v10.21.0
4 verbose run-script [ ‘prebuild’, ‘build’, ‘postbuild’ ]
5 info lifecycle kpi@0.1.1~prebuild: kpi@0.1.1
6 info lifecycle kpi@0.1.1~build: kpi@0.1.1
7 verbose lifecycle kpi@0.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle kpi@0.1.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/src/kpi/node_modules/.bin:/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/srv/src/kpi/node_modules/.bin
9 verbose lifecycle kpi@0.1.1~build: CWD: /srv/src/kpi
10 silly lifecycle kpi@0.1.1~build: Args: [ ‘-c’, ‘webpack --config webpack/prod.config.js’ ]
11 silly lifecycle kpi@0.1.1~build: Returned: code: 1 signal: null
12 info lifecycle kpi@0.1.1~build: Failed to exec build script
13 verbose stack Error: kpi@0.1.1 build: webpack --config webpack/prod.config.js
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:198:13)
13 verbose stack at ChildProcess. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:198:13)
13 verbose stack at maybeClose (internal/child_process.js:982:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid kpi@0.1.1
15 verbose cwd /srv/src/kpi
16 verbose Linux 5.4.0-1037-gcp
17 verbose argv “/usr/bin/node” “/usr/bin/npm” “run” “build”
18 verbose node v10.21.0
19 verbose npm v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error kpi@0.1.1 build: webpack --config webpack/prod.config.js
22 error Exit status 1
23 error Failed at the kpi@0.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Additional details

Since the `manage.py collectstatic ` comand worked, now I have a semi-updated version of the site running on kf - some of the logos and icons have changed but most of the functional code has not. 

Admittedly I'm not a very skilled docker user, or even linux for that matter, so I'd appreciate anyone pointing me in the right direction to solve the issue.

**Comment by jnm** [comment]
Let's proceed at https://community.kobotoolbox.org/t/issues-with-kpi-updates-build-errors/16754, since this error pertains to your individual situation and is not a bug in any code within this repository.
