### ISSUE TITLE
'No inspectable targets' error in npm-test (GitHub CI)

### ISSUE THREAD

**Issue by p2edwards** [kobotoolbox/kpi#4337]
## Description

🐛 In CI, the `npm-test` workflow might hang up to 6 hours or until manually cancelled, instead of running the tests and succeeding/failing based on that.

## Steps to Reproduce

1. On an open PR, push a git commit where `npm install`, `npm run build` and ideally `npm run test` succeed when run locally.
2. Wait 3-5 minutes for the `npm-test` flow to get to the `npm run test` stage.
3. Cross your fingers. You might see the intermittent error, or you might see the expected behavior.

## Expected behavior 

The CI action for `npm run test` succeeds if the tests pass, and fails if they don't.

## Actual behavior 

Too often, the CI action for `npm run test` hangs with the error '`No inspectable targets`', and then waits up to 360 minutes before terminating itself. 

```
Promise Rejection:  Error: No inspectable targets
    at defaultTarget (/home/runner/work/kpi/kpi/node_modules/chrome-remote-interface/lib/chrome.js:48:23)
    at Chrome._fetchDebuggerURL (/home/runner/work/kpi/kpi/node_modules/chrome-remote-interface/lib/chrome.js:192:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Chrome._start (/home/runner/work/kpi/kpi/node_modules/chrome-remote-interface/lib/chrome.js:139:25)
```

- Example: [this run](https://github.com/kobotoolbox/kpi/actions/runs/4406745926/jobs/7719419067), and many more.

## Additional details
 
This appears to be a fairly common experience when using Chrome's remote interface.

- My first simple fix, [extending the maxRetries](https://github.com/kobotoolbox/kpi/pull/4323/commits/ffdd3d8416e8421592c0d248f7896a47f60fe487), seemed robust locally but still [failed on CI](https://github.com/kobotoolbox/kpi/actions/runs/4406745926/jobs/7719419067) sometimes.
- My second simple fix [increasing the pollingInterval](https://github.com/kobotoolbox/kpi/blob/9a8e187403e316ea40764b2ad737a5295c8330ec/.github/workflows/npm-test.yml#L32) might work.
   - It has an early timeout that should make it easier to do the busywork of manually retriggering the test if it does fail.

I haven't seen it fail yet, so if #4323 gets merged and we don't see this problem again for a while, we can probably close this issue.

If that second fix doesn't work:

- We may need to write some standalone JavaScript instead of using CLI arguments. Some of the repos that came up in my searches earlier, particularly the more "infrastructural" ones, went this way.
- 'mocha-chrome' hasn't had an update for a while. It may be that its direct dependencies has a good answer for this already.

**Comment by p2edwards** [comment]
This appears to be resolved since [`9a8e1874`](https://github.com/kobotoolbox/kpi/commit/9a8e187403e316ea40764b2ad737a5295c8330ec). 

The fix: adding `--chrome-launcher.connectionPollInterval=5000` to our CI script.

```yaml
      - name: Run Tests, with mocha-chrome
        run: npx mocha-chrome test/tests.html --chrome-launcher.connectionPollInterval=5000
        timeout-minutes: 1 # early timeout in case of https://github.com/kobotoolbox/kpi/issues/4337
```

Re-open this issue if the tests timeout.
