### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signal_processor'

### ISSUE THREAD

**Issue by danielmwai** [kobotoolbox/kpi#955]
The following error  happens  when the  running   python manage.py   syncdb --noinput  but when  i  comment  out  the  code  in  apps.py  on the ready function  it runs without any error.  Can it  lead to problems later  ? 

(kpi) falkan@falkan:~/apps/CODING_DEV_APPS/SURVEY_PROJECTS/kpi$ python manage.py   syncdb --noinput  
/home/falkan/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/kpi/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

INFO: Successfully connected signals for Haystack indexing.
INFO: Haystack signals connected on the first try! Perhaps remove workaround code in `SignalProcessor.__init__()`.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/falkan/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/kpi/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/falkan/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/kpi/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/falkan/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/kpi/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/falkan/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/kpi/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/falkan/apps/CODING_DEV_APPS/SURVEY_PROJECTS/kpi/kpi/apps.py", line 11, in ready
    haystack.signal_processor.load_models()
AttributeError: 'module' object has no attribute 'signal_processor'

**Comment by dorey** [comment]
The file `kpi/apps.py`, which is where the error is occuring, no longer exists. I would recommend  removing all the compiled `.pyc` from the repo.

`find . -name \*.pyc -delete`

**Comment by danielmwai** [comment]
@dorey  your solution works
